source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'XBContact_Example', :exclusive => true do
  pod "XBContact", :path => "../"
end

target 'XBContact_Tests', :exclusive => true do
  pod "XBContact", :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
